### ISSUE TITLE
Default values?

### ISSUE THREAD

**Issue by burberius** [ZyorTaelon/eveapi#110]
What should be the default value for numbers that didn't have data in result: zero or null?

**Comment by burberius** [comment]
In my opinion they should be null. But then you have to check it when accessing it.

**Comment by GoldenGnu** [comment]
I agree that it should be null, as that is how everything not numbers work

**Comment by burberius** [comment]
So lets change change all occurrences of int or long or double in responses and models.

We have to change some logic in the online tests, too, I guess.

**Comment by burberius** [comment]
We will leave that, as the api is deprecated and will be removed within 18 months.
