### ISSUE TITLE
SecurityParserOnlineTest always have CorporationRole.getRoleDescription() as null

### ISSUE THREAD

**Issue by burberius** [ZyorTaelon/eveapi#114]
Leave it or remove it?

My opinion: Leave it, we don't know if it is not set in any case.

**Comment by GoldenGnu** [comment]
Documentation does not include it and it's not returned by any of the test API Keys.
Therefor, I conclude it's never returned. Hence, I think it should be removed, however, It's a lot of work to remove it, so, I'm not sure It's worth it.

Reference:
https://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/corporation/corp_membersecurity.html

**Comment by burberius** [comment]
I will ask if I can have a corp key and test if it is missing there, too. Or if I can add a corp role description in my own highsec corp.

**Comment by burberius** [comment]
We wont fix that, because the API is deprecated.
