### ISSUE TITLE
Online Tests

### ISSUE THREAD

**Issue by burberius** [ZyorTaelon/eveapi#50]
We should create some online test, to verify all endpoints still exist and the fields are all valid.
Therefore we will need a Corp and a Character API. I will ask in the Slack Devfleet channel if there exists an official one.

The online test should be executed as non default profile only. This can be done in the CI builds.

**Comment by burberius** [comment]
There is no public API key for testing. :-(
I'll try to create a trial account and also create a "demo" corp for that.

**Comment by ZyorTaelon** [comment]
Problem with a trail account is that it only lasts a limited time. It would
really only work with an alt character on an existing account that'll stay
active for a long long time.

**Comment by burberius** [comment]
From Devfleet:
(13:07:23) luciadenniard: you can still use the API key when unsubbed

**Comment by ZyorTaelon** [comment]
Ok worth a shot.

**Comment by Marcon** [comment]
Well... I can make api key for you, guys, on my cyno alt(and make corporation for it).

**Comment by burberius** [comment]
That would be so great!
But keep in mind we would need a full API key, so we can test all endpoints.

**Comment by Marcon** [comment]
Yes. Full api, but it will be limited to one character on account(I can't make other characters on account public).

**Comment by burberius** [comment]
Only a single character would be fine!
Could you post them here?
Then I will start on some online integration tests, when I find the time.

**Comment by Marcon** [comment]
KeyID: 4428355
vCode: Efnyja8S6pawB4EzefgZBFLDWGGTv0U9RZTfC6bD3vZ1pIc45FdgOUiCL6bpEssm

In ~5 minutes i train corporation management on this alt, make new corporation an then i will post corporation key

**Comment by Marcon** [comment]
Fell free convo/mail character Kasarch ingame, if you need some actions with keys or test corporation.

**Comment by burberius** [comment]
With online test, we would have found #58 ...

**Comment by burberius** [comment]
Here is some example, how I did the online tests in my eve-crest API, then they could be run with a maven profile:
https://github.com/burberius/eve-crest/blob/master/pom.xml#L135

**Comment by GoldenGnu** [comment]
I have started coding this.

Some of the API calls can not be tested Marcon's keys, because they return empty results (The contracts API, for example). I will post the full list when I have it.

**Comment by Marcon** [comment]
@GoldenGnu Well i can make some contracts for test character and corporation, but it be finished contract. 
If you need some actions with test character - tell me, what you need.

**Comment by GoldenGnu** [comment]
@Marcon
I will post the full list here when I have finished all the tests. I'm slowly working my way though all the API calls. I don't have a lot of time to work on it each day, so, it will take some time to complete everything.

Even small changes to the char/corp will invalidates existing online test. So, I prefer adding everything missing in one go and then fixing all the tests. Then the char/corp can be kept static.

**Comment by GoldenGnu** [comment]
@Marcon
I finally finished the first stage of writing the tests; checking all the API calls for data.

I now have a list of all the APIs that are missing data: http://pastebin.com/BrmZ9uW1
I realize it is a major task to add all the needed data in game...
Some of the data may not be possible to add (like Alliance stuff) and some of the data may change too much to rely on for static testing. But, lets see how far we can get...

o7

**Comment by burberius** [comment]
Any news on that?
I'm currently working on #58 and would like to use your code to add online tests for KillMails.

**Comment by GoldenGnu** [comment]
I was waiting for @Marcon to reply.

The only thing I have done so far is to created all the test classes to figure out what APIs was empty and then I pretty much gave up tbh, because half of them didn't return any data and the rest changed faster than I could write the tests.

I don't think it's doable, as a million things expire in the API after a while and then you have to go in game and create data and then fix all the tests.

**Comment by burberius** [comment]
Those online tests should not check the exact data, but test
* if there was an error
* data is returned
* all field have content (not null and no empty string)
* perfect would be if we detect if new field were added

I'll try to do an example with the KillMail Endpoint, perhaps I have to kill @Marcon alt for that. ;-)

**Comment by GoldenGnu** [comment]
That would be perfect. A working prototype would be of great help to finish this issue.
I slowly started working on the tests today, just checking everything for null/zero.
Of course, most of the test will fail, until the data is created in-game.

I still see two problems:
1) Detecting new fields may be hard (but, would be really awesome)
2) I think some fields can be valid and null (but, I'm not 100% sure)

Anyway, look forward to seeing your results :)

**Comment by Marcon** [comment]
Oh god. I forgot about that alt. Sorry guys, account with that alt currently not payed. I'm currently working on two big projects and have no time for eve.

**Comment by GoldenGnu** [comment]
No worries...

If I read the devblog right, they're going to make eve-online free to play in November (with restrictions), so, that should make the char and corp accessible again.

If needed I can provide a corp/char key to my alts for use until then.

**Comment by GoldenGnu** [comment]
I finished writing all the online tests. It simply test if the value is null or not for all fields of all classes. It can easily be extended to also check if String/Collection/Map are empty and Numbers are zero
I'm currently trying to fix as many false positives as possible (a lot of values are allowed to be null).
Then I will commit it to my fork.

All the test are never going to pass, but, I already found quite a few minor bugs.

**Comment by burberius** [comment]
I currently also write on online tests for my KillMail changes and use reflection to walk over the beans.
I hope we can somehow merge our stuff together.

For detecting new fields, we could match the number of attributes in the handlers to the number of field of the destination object. I haven't added that yet.

**Comment by GoldenGnu** [comment]
Reflection is the way to go, that way the tests will always be up to date. I will update my tests with your code once you're done. :)

Detecting new fields would be really really great...

**Comment by burberius** [comment]
Done, see my last commit.

You can run the online tests with:
*mvn clean test -Ponline*

**Comment by burberius** [comment]
Online tests are implemente now, some problems are left over.
See #80

**Comment by burberius** [comment]
@Marcon Can you please update the character key to include the ChatChannel rights, could be there are some other unchecked rights, too.

**Comment by Marcon** [comment]
ChatChannel not available for corproration keys.
Here key for character with enabled chat channels options
id: 5669026
vcode: Ud0aGh79j4ugLNmBhct4o9cHjbzFOmoMkbemN0ZSolsDfX0JXpXob4OwUU9Dw4Hu

also on corporation key enabled bookmarks option

**Comment by burberius** [comment]
Thank you, I will integrate them tomorrow. 
So it looks like we are missing a bookmark endpoint, but perhaps it's in Crest...

**Comment by Marcon** [comment]
https://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/corporation/corp_bookmarks.html

**Comment by burberius** [comment]
I wonder what those should be good for. 
It would be nice if you could change them, delete old ones for example.

**Comment by Marcon** [comment]
Created new one. Also now this character going to jita using autipilot, so we have chance to get killmail for this character(not good chance, cause Stain is dead region)

**Comment by burberius** [comment]
Updated key
