### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by burberius** [ZyorTaelon/eveapi#51]
We should clean up the pom and try to publish to maven central.

Requirements can be found here: http://central.sonatype.org/pages/requirements.html
Repository to deploy to: http://central.sonatype.org/pages/ossrh-guide.html

The release and deploy job should be done by jenkins automatically.

**Comment by burberius** [comment]
I just applied for a repository to deploy it to central:
https://issues.sonatype.org/browse/OSSRH-18342

**Comment by ZyorTaelon** [comment]
Don't we need to configure pgp/gpg signing as well before we can deploy to
central?

**Comment by burberius** [comment]
Right, I will do that all on Jenkins. Build a release with source, Java Doc, sign it and then deploy it.

**Comment by ZyorTaelon** [comment]
I think the sources and javadoc are already configured in the pom.

**Comment by burberius** [comment]
We got accepted to Sonartype's OSS repository. From there there artefacts will be moved to central. 
Now I just have to finish the Jenkins job.

**Comment by ZyorTaelon** [comment]
Sweet!

**Comment by burberius** [comment]
First successful release with Jenkins
http://didge.my-wan.de/jenkins/job/GitHub%20eveapi%20-%20Release%20and%20deploy/8/
I release version 6.0.0 as it is a big step! ;-)
https://oss.sonatype.org/#nexus-search;quick~eveapi

Theoretical it should be available in Maven Central soon...

**Comment by burberius** [comment]
It's in Maven Central now:
https://repo1.maven.org/maven2/com/beimin/eveapi/

So we can close #51
