### ISSUE TITLE
Chat Channel Information

### ISSUE THREAD

**Issue by burberius** [ZyorTaelon/eveapi#57]
Chat Channel Information are now available via xml, so we should add those too.
https://developers.eveonline.com/blog/article/chat-channel-info-available-in-xml-api

**Comment by burberius** [comment]
I started on this.

**Comment by burberius** [comment]
@GoldenGnu Can you have a look at the online test? I can't get it to run.

Also what do you think about the Accessor? It looks like some have 2 fields, some have four. Do you think it's OK to use one class for both?
I used Lists as container and not Sets, what do you think about that?

**Comment by GoldenGnu** [comment]
1) Committed a fix the online test. But, I do not have a test char with any data, so, I can not validate it works with data.
2) I do not think it's good to return classes that always have some fields as null.
3) I think we should decide if we want to go with List or Set and then use that everywhere.

**Comment by burberius** [comment]
Split Accessor to one with just name and the other with name + reason + untilWhen.

**Comment by burberius** [comment]
Done with #106
