### ISSUE TITLE
SAXNotRecognizedException on Android

### ISSUE THREAD

**Issue by Marcon** [ZyorTaelon/eveapi#61]
Hi. I'm trying to use eveapi lib in my app, but after upgrade to 6.0.0 I'm getting 
```
org.xml.sax.SAXNotRecognizedException: http://javax.xml.XMLConstants/feature/secure-processing
    at org.apache.harmony.xml.ExpatReader.setFeature(ExpatReader.java:130)
    at com.beimin.eveapi.connectors.ApiConnector.getApiResponse(ApiConnector.java:55)
    at com.beimin.eveapi.connectors.ApiConnector.execute(ApiConnector.java:43) 
    at com.beimin.eveapi.parser.shared.AbstractApiParser.getResponse(AbstractApiParser.java:55) 
    at com.beimin.eveapi.parser.shared.AbstractApiParser.getResponse(AbstractApiParser.java:39) 
    at com.beimin.eveapi.parser.account.ApiKeyInfoParser.getResponse(ApiKeyInfoParser.java:25)
```

and there is my code
```java


            new AsyncTask<Void, Void, Void>() {
                @Override
                protected Void doInBackground(Void... params) {
                    ApiAuthorization auth = new ApiAuthorization(4428366, "5TDpVttAXfTtJhWvPYKZnVfwIZPj8kAIDGa3YzP3MlVRwa2pYI6KP2qXBZseSoKa");
                    ApiKeyInfoParser parser  = new ApiKeyInfoParser();
                    try {
                        ApiKeyInfoResponse response = parser.getResponse(auth);
                    } catch (ApiException e) {
                        throw new RuntimeException(e);
                    }
                    return null;
                }
            }.execute();
```

**Comment by Marcon** [comment]
5.2.0 from mavencentral have same problem.
5.1.3 from old jar working fine.

**Comment by burberius** [comment]
The problem could be, that the maven central versions are built with Java 8.
What Java version do you use in Android?

**Comment by Marcon** [comment]
1.8.0_60 but android uses java level 7.0

**Comment by burberius** [comment]
I just released 6.0.4, compiled with java 7.
Could you give it a try?

**Comment by Marcon** [comment]
Yes. I will try on this weekend.

**Comment by Marcon** [comment]
Nope. Same exception. :(
Sorry for delay - has lots of work.

**Comment by Marcon** [comment]
Ok. After almoast hour of googling, I found solution that works for me.
https://github.com/Marcon/eveapi/commit/5c676e7472f860e30b0cdd05c85995451909f429

**Comment by burberius** [comment]
I will add that change to our repository after my holidays.
But as it's a security problem, I will log at least a warning about that!

**Comment by Marcon** [comment]
@burberius Maybe better to make some configuration option to allow user skip setting FEATURE_SECURE_PROCESSING feature, in that case user can disable secure processing for own responsibility?

**Comment by burberius** [comment]
I created a release 6.0.5 with this fix, will be on maven central shortly.
