### ISSUE TITLE
Project Status (Dead or Alive?)

### ISSUE THREAD

**Issue by GoldenGnu** [ZyorTaelon/eveapi#62]
Hi, I'm Golden Gnu from jEveAssets project. Is this project still alive?
I can see issues and pull requests have gone unanswered since ~December?
If help is needed to keep the library alive, I would like to volunteer my time :)

I would also like to contribute a few things:
1) Blueprint API
2) A few Java 6 compatibility changes:
- Long.compare(long, long) not compatible with Java 6 (only used twice)
- camel-jetty 2.14.4 is the latest version that still supports Java 6

**Comment by burberius** [comment]
Hi

The project is not dead, but not very active either.
I'm currently not playing a lot and also stopped coding on my projects in my spare time, so eveapi is inactive too.
I'll try to take care of this project, so your changes are welcome.

Bye, Burb

**Comment by burberius** [comment]
In my opinion we should drop the backward compatibility. Java 6 is end of life since February 2013 and Java 7 since April 2015. Nobody should use such old versions!
Also some of the new features are very nice.

**Comment by GoldenGnu** [comment]
Thank you for the reply. Good to hear the project is still going, even if it is a bit slow.
As long as I can contribute bug fixes via pull requests, all is good.

1) While I agree that none should use Java 6, I still think It's worth keeping backward compatibility.
But, of course I respect your decision.

2) I will try to create the Blueprint API pull request doing the week.

3) Would you be interested if I started coding #50?

**Comment by burberius** [comment]
Sure, that would be great. I can then add a Jenkins job that runs those tests once a week.

**Comment by GoldenGnu** [comment]
Finally got around to create the pull request. I will start working on the online tests next.

**Comment by burberius** [comment]
Reanimated! ;-)
