### ISSUE TITLE
org.powermock should have test scope

### ISSUE THREAD

**Issue by GoldenGnu** [ZyorTaelon/eveapi#70]
I'm pretty sure the ``org.powermock`` dependencies are only used in test?
I only found them used in: ``com.beimin.eveapi.connectors.ApiConnectorTest``

They should have the scope set to "test" or they will be included when adding the EVEAPI as a dependency to another project.

```
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-mockito</artifactId>
            <version>1.6.5</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4</artifactId>
            <version>1.6.5</version>
            <scope>test</scope>
        </dependency>
```

the changed part is **``<scope>test</scope>``** in both dependencies.

Again, I apologize for not creating a pull request and creating more work for you. I'm really really bad at git, sorry...

**Comment by GoldenGnu** [comment]
Added pull request #73 for this issue

**Comment by burberius** [comment]
Thanks for your pull requests, building a new version now.
