### ISSUE TITLE
Naming of classes

### ISSUE THREAD

**Issue by GoldenGnu** [ZyorTaelon/eveapi#75]
A few classes fall outside the normal naming conventions:
```
com.beimin.eveapi.model.shared.EveAccountBalance > AccountBalance
com.beimin.eveapi.parser.pilot.PilotAssetListParser > AssetListParser
com.beimin.eveapi.parser.pilot.PilotAccountBalanceParser > AccountBalanceParser
```
While I agree having both ``com.beimin.eveapi.parser.pilot.AccountBalanceParse`` and ``com.beimin.eveapi.parser.corporation.AccountBalanceParse`` named the same is not optimal, that is the way all the other APIs do it.

It may be worth considering adding a prefixes to the parsers class names. I would suggest ``Corp`` for corporation APIs and ``Char`` or no prefix for characters APIs.

**Comment by burberius** [comment]
I was struggling too with the naming, but was to lacy to do it yet.
But your suggestion is good, you need to see from the class name what it is, without looking at the package.
Will you do the changes? Otherwise I'll do it when I find the time.

**Comment by GoldenGnu** [comment]
Thank you for accepting my suggestion :)

I will be happy to do it. I will try to get it done in a timely manner, but, I can not promise when it will be done, as jEveAssets take most of my free time ATM.

I have a few questions:
1) You want characters parsers to have ``Char`` prefix or no prefix?

2) You want all corporation and characters parser to get the prefix or just the ones that have both a corporation and characters parser?

3) You want some of other packages (account/eve/map/calllist) to get a prefix, as well?

4) I'm not sure it's a good idea, but, I want to bring it up, as this will break everything for everyone, anyway:
We could also add a prefix to all data classes ex:  ``Api`` ``Eve`` `EveApi`. As, I said, I'm not sure It's a good idea, but, I think it needs to be decided before we do this major refactoring.

**Comment by burberius** [comment]
No hurry, it's only a hobby.

> 1) You want characters parsers to have Char prefix or no prefix?
> 2) You want all corporation and characters parser to get the prefix or just the ones that have both a corporation and characters parser?
I would say where we have Corp or Char add those as prefix, like:
CharAccountBalance <--> CorpAccountBalance

3) You want some of other packages (account/eve/map/calllist) to get a prefix, as well?
They are not shared, so I don't know what to change there, they sound all well for me.

4) I'm not sure it's a good idea, but, I want to bring it up, as this will break everything for everyone, anyway:
We could also add a prefix to all data classes ex: Api Eve EveApi. As, I said, I'm not sure It's a good idea, but, I think it needs to be decided before we do this major refactoring.
Do don't get what you mean with the prefix here. Could you give another example, please?

I would change the version of the new release to 7.0.0 as it breaks the api heavily. So we can do more changes like that before releasing. ;-)

**Comment by GoldenGnu** [comment]
4) Example for the data classes: ``EveAsset`` or ``EveApiAsset`` or ``ApiAsset`` instead of just ``Asset``
Again, as I already said, I'm not sure it's a good idea, but, I still think it's at least worth considering, before refactoring the parsers

**Comment by burberius** [comment]
Was done by @GoldenGnu with #82
