### ISSUE TITLE
Restructuring of packages

### ISSUE THREAD

**Issue by burberius** [ZyorTaelon/eveapi#76]
@GoldenGnu 
What is your opinion about changing the package structure like this:

*From:*
com.beimin.eveapi.handler.pilot
com.beimin.eveapi.model.pilot
com.beimin.eveapi.parser.pilot
com.beimin.eveapi.response.pilot

*To:*
com.beimin.eveapi.pilot.handler
com.beimin.eveapi.pilot.model
com.beimin.eveapi.pilot.parser
com.beimin.eveapi.pilot.response

It could be better to combine all classes by their area (*pilot*) and put the functional package part afterwards.

I'm not sure which way is better, changing would be OK, when we do a major release, but it would be more work to adapt a project to that.

**Comment by GoldenGnu** [comment]
I think you should choose whatever structure makes coding EveAPI easier. That is the most important part for me. The IDE will handle the imports no matter where we put the classes.
If the new layout make stuff easier for you, that is the way to go.

I must also admit, that I have very little knowledge about this subject, so, I may not be the best person to answer this.

**Comment by burberius** [comment]
I'll leave it as it is.
It looks like we are the only ones using EveApi anyways. ;-)
