### ISSUE TITLE
Check handlers for parsing of currentTime and cachedUntil

### ISSUE THREAD

**Issue by burberius** [ZyorTaelon/eveapi#77]
See *eveapi/src/main/java/com/beimin/eveapi/handler/shared/KillMailHandler.java* in commit 697c4b813bf264193325fc05cb8825b047229a36

In endElement you have to add an else at the end:

```java
} else {
            super.endElement(uri, localName, qName);
}
```

**Comment by burberius** [comment]
@GoldenGnu You checked that when you implemented the online tests, didn't you?

**Comment by GoldenGnu** [comment]
Yes, the online test does check if currentTime and cachedUntil is null.
I though I added the ones I found to issue #80, but, it looks like I forgot.
