### ISSUE TITLE
Online Test: Results

### ISSUE THREAD

**Issue by GoldenGnu** [ZyorTaelon/eveapi#80]
### New Fields:
**com.beimin.eveapi.model.pilot.UpcomingCalendarEvent**
~~ownerTypeID :: int (typeID is always an int, right?)~~
**com.beimin.eveapi.model.eve.CharacterEmployment**
~~recordID :: long
corporationName :: String~~
**com.beimin.eveapi.response.eve.CharacterInfoResponse**
~~bloodlineID :: whole number
ancestryID :: whole number
ancestry :: Ancestry (enum)
nextTrainingEnds :: Date~~
**com.beimin.eveapi.model.eve.Station**
~~x :: long~~ [1]
~~y :: long
z :: long~~
**com.beimin.eveapi.model.pilot.Notification**
~~senderName :: String~~
**com.beimin.eveapi.model.pilot.MailMessage**
~~senderTypeID :: int (typeID is always an int, right?)~~
**com.beimin.eveapi.model.map.FacWarSystem**
~~owningFactionID :: whole number
owningFactionName :: String
victoryPoints :: whole number
victoryPointThreshold :: whole number~~
**com.beimin.eveapi.response.pilot.CharacterSheetResponse**
~~homeStationID :: locationID
bloodLineID :: whole number
ancestryID :: whole number
factionID :: whole number
freeSkillPoints :: whole number
freeRespecs :: whole number
cloneJumpDate :: Date
lastRespecDate :: Date
lastTimedRespec :: Date
remoteStationDate :: Date
jumpActivation :: Date
jumpFatigue :: Date
jumpLastUpdate :: Date~~
**com.beimin.eveapi.model.shared.IndustryJob**
~~successfulRuns :: whole number~~
**com.beimin.eveapi.model.shared**
~~owner1TypeID :: int
owner2TypeID :: int~~

### New Rowsets
**com.beimin.eveapi.response.pilot.CharacterSheetResponse**

~~jumpClones~~
- ~~jumpCloneID :: long/int~~
- ~~typeID::int~~
- ~~locationID::long~~
- ~~cloneName::String~~

~~jumpCloneImplants~~
- ~~jumpCloneID::long/int~~
- ~~typeID::int~~
- ~~typeName::String~~

~~implants:~~
- ~~typeID::int~~
- ~~typeName::String~~

**com.beimin.eveapi.model.account.AccountStatus**

~~multiCharacterTraining:~~
- ~~trainingEnd :: Date?~~

**com.beimin.eveapi.response.pilot.MedalsResponse**

~~Everything is put into a single list, but, the result have two rowsets:~~
- ~~currentCorporation~~
- ~~otherCorporations~~

### Dead:
~~com.beimin.eveapi.response.pilot.SheetParserOnline.certificates
com.beimin.eveapi.response.pilot.CharacterSheetResponse.certificates
eveapi/src/main/java/com/beimin/eveapi/model/pilot/Certificate.java
com.beimin.eveapi.response.corporation.CorpSheetResponse.allianceName (validated)~~

### Bug:
~~SecurityLogParser.cachedUntil :: return null (does not call super.endElement )
com.beimin.eveapi.model.shared.Contact.labelMask :: not int > is long
com.beimin.eveapi.model.shared.ContactLabel.labelID :: not int > is long~~

[1]
Coordinates used to always be a double, maybe they moved all coordinates to long?
I check ConquerableStationList (where stations are used) and x, y, z are all long/int

**Comment by GoldenGnu** [comment]
com.beimin.eveapi.model.account.AccountStatus.getUserID :: removed from the API?

**Comment by GoldenGnu** [comment]
Bug:
com.beimin.eveapi.parser.pilot.ResearchParser :: version mismatch

**Comment by burberius** [comment]
*com.beimin.eveapi.model.account.AccountStatus.userID* looks like it was removed:
http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/account/account_accountstatus.html

**Comment by burberius** [comment]
http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/character/char_research.html
No info about the version, so I would just adjust it.

**Comment by burberius** [comment]
When changes to the online tests are done, be sure that currentTime and cachedUntil are not null!

**Comment by GoldenGnu** [comment]
Completed with merge #102
